### ISSUE TITLE
Add separate LEDs for all backlight settings

### ISSUE THREAD

**Issue by K900** [Wattos/logitech-g710-linux-driver#1]
Bitmasks are good and all, but having a user friendly (or at least user friendlier) way to set backlight would be cool.

**Comment by Wattos** [comment]
Thanks,

That was my first approach (having a separate attribute for every led), but then there must be some "housekeeping" done on the driver level. E.g. the driver must remember the current values for the other leds otherwise setting led_m1 might reset the other values.

Having said that, I will look at it again and see if it can be fixed.

**Comment by K900** [comment]
It's totally possible, I did it in my code. Just read the bitmask for every
read, and read-change-write for every write. I'll try to merge my changes
later,  because I like your code much better then mine.

2013/5/12 Wattos notifications@github.com

**Comment by Wattos** [comment]
Sounds good. Im looking forward to the pull request.

**Comment by Wattos** [comment]
@K900 Did you manage to implement a fix for this issue?

**Comment by K900** [comment]
No, not yet. I'm out of town for a while, so I don't have access to the
keyboard.

2013/7/4 Wattos notifications@github.com
