### ISSUE TITLE
can't get driver to work

### ISSUE THREAD

**Issue by wxl** [Wattos/logitech-g710-linux-driver#11]
**seems installed:**
- `grep -r g710 /lib/modules`:

```
Binary file /lib/modules/3.2.0-59-generic-pae/extra/hid-lg-g710-plus.ko matches
Binary file /lib/modules/3.2.0-59-generic-pae/modules.alias.bin matches
/lib/modules/3.2.0-59-generic-pae/modules.dep:extra/hid-lg-g710-plus.ko: kernel/
drivers/hid/usbhid/usbhid.ko kernel/drivers/hid/hid.ko
Binary file /lib/modules/3.2.0-59-generic-pae/modules.dep.bin matches
/lib/modules/3.2.0-59-generic-pae/modules.alias:alias hid:b0003v0000046Dp0000C24
D hid_lg_g710_plus
Binary file /lib/modules/3.2.0-48-generic-pae/extra/hid-lg-g710-plus.ko matches
Binary file /lib/modules/3.2.0-48-generic-pae/modules.alias.bin matches
/lib/modules/3.2.0-48-generic-pae/modules.dep:extra/hid-lg-g710-plus.ko: kernel/
drivers/hid/usbhid/usbhid.ko kernel/drivers/hid/hid.ko
Binary file /lib/modules/3.2.0-48-generic-pae/modules.dep.bin matches
/lib/modules/3.2.0-48-generic-pae/modules.alias:alias hid:b0003v0000046Dp0000C24
D hid_lg_g710_plus
```
- `lsmod | grep g710`:

```
hid_lg_g710_plus       13036  0
usbhid                 41937  1 hid_lg_g710_plus
hid                    81731  2 hid_lg_g710_plus,usbhid
```

however, i can't seem to get the M keys to do anything nor the G keys to do anything but return their number. so according to xev, M keys are nothing and G keys are 1-6.

furthermore, i can't seem to find anything useful in kde's settings that can provide any assistance.

maybe i don't understand how to use this?

**Comment by IcyPalm** [comment]
I am running into the same problems. Cannot use the M keys and the G keys return numbers.

I am running Elementary OS Luna

**Comment by RPG-Master** [comment]
I'm having the same issue.

This is on Ubuntu 14.04 64-bit

**Comment by alexandra-zaharia** [comment]
Same problem here, on Kubuntu 14.04 64-bit.

The problem is that the G keys print out numbers (1 through 6) and when I try to bind them via AutoKey, the block of text I want to insert using the G keys is preceded by that number. Is there any way I can make them _not_ print out numbers 1 through 6?

**Comment by MrGid** [comment]
This issue is caused of the behavior of udev. The udev rule is just loaded after a trigger event for the keyboard. The simplest solution is pulling the usb and putting it in again. Then xev should give you proper values for the G keys.
If this solves the issue you can run following command to trigger this event without climbing behind your pc.
udevadm trigger --type=devices --action=add --subsystem-match=hid

**Comment by alexandra-zaharia** [comment]
Thank you for your suggestion, MrGid. Unfortunately I am now using Ubuntu 12.04 at work (kernel 3.2) and this solution does not seem to work for this configuration (I tried unplugging and replugging the USB cable and adding the trigger by hand via udevadm, as you've suggested).

On this system configuration, the problem seems even deeper -- the G keys have keycodes 10 through 15 as displayed by xev, and these are the same keycodes as those of keys labeled 1 through 6. Moreover, the M keys don't register at all (xev doesn't get notified by the keypress/keyrelease events for the M keys).

I'll try your suggestion on my home computer running on a more recent kernel and see how it goes. At least there I do get most of the time keycodes for G keys different from the keycodes of the number keys, and the M keys do register without any issue at all.

**Comment by MrGid** [comment]
hm, this worked for me on Ubuntu 14.04, sadly i doesn't have further suggestions for you.
good luck

**Comment by alexandra-zaharia** [comment]
I confirm your fix works on Kubuntu 14.04 64b, MrGid, on kernel version 3.13.0-27-generic. It is effectively the fact that the trigger needs to be set and then the G keys get their correct keycodes, ranging from 195 through 200. 

It was on a Ubuntu 12.04 machine I have at work that this didn't work.

Thank you very much for your help and kudos to the author of the driver for taking the time to render this wonderful keyboard usable under Linux!

**Comment by RPG-Master** [comment]
I'm not sure if I might have messed something up since I removed the driver several months ago, but after reinstalling it and trying MrGrid's solution, I'm not getting any different results.

**Comment by wxl** [comment]
3.13.0-35-generic on Kubuntu 14.04.1 LTS. Ran the `udevadm` trigger. I
assume you don't have to `sudo` given the 0 exit code. G keys are still
number keys.

**Comment by wxl** [comment]
Well, 3.13.0-40-generic on Kubuntu 14.04.1 LTS without `sudo` did not work. With it, all is well! I'm calling this, the original problem, closed.
