### ISSUE TITLE
Question: How to automatically update KB driver modules with kernel updates

### ISSUE THREAD

**Issue by mcrajah** [Wattos/logitech-g710-linux-driver#17]
Hi, I love that I can use the extra keys on my G710+ on Linux, thanks for the driver. I  cannot get keys G3 and G4 to work, not sure why, but all other extra keys are getting registed. I also find that each time my kernel upgrades, I have to reinstall the driver. Is there anyway to make this automatic?

Thanks,
Rajah
uname -a: Linux Dexter 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux

**Comment by XenHat** [comment]
_Preface: I do not want this comment to appear as an attempt to bash your report. I am simply trying to help both the developers and yourself :) Bug reports are always appreciated, however vague sentences and information left to guesswork often make reports useless._

It would help the developer/s if you could provide a bit more precise information regarding your issue:
**What stopped working** and **What still works** with the new kernel?

According to your report you can't use **G3** and **G4**, so the developer/s have to assume that G1 and G2 keys still work, and assuming is bad for software development.

A bit of friendly advice regarding the title of your issue ("Drived stopped working with new Kernel" at the time of writing of this comment): Aside the typo (Drived->Driver), since the ~~driver~~ module **still works** to some degree (guesswork), I would advise against the use of 'sensationalist' titles (since it claims that the ~~driver~~ module  simply isn't working at all) as it makes sorting and prioritization of bugs a bit hairy. (Might I suggest "**G-Keys partially working after kernel update (KERNEL_VERSION_HERE)**" ?)

Regarding the second part of your report, automatic third-party kernel drivers re-installation can be enabled/implemented with [DKMS](https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support), however I do not know if this ~~driver~~ module supports it. (I'm also not a kernel developer so I'm a bit out of touch when it comes to those technicalities).

**Comment by mcrajah** [comment]
I apologize for the lack of details, somehow when I was typing the details, it seems to make sense to me, after reading your note, I can see the confusion.

I followed all the instructions and setup the driver to work with my kernel. After setting up the driver, I was able to use M1, M2, M3 and MR buttons. I also was albe to use G1, G2, G5 and G6. I was unable to use G3 and G4 buttons as those key presses were not being registered. I did not try to setup the LEDs for M1-MR as I did not find the device entries as described in the instructions. However, I did not care, as I could still use the buttons. 

Last week, there was a new kernel release (3.18.6) and after the new kernel booted, the drivers did not work as they were not loaded, which led to my question on how to automatically load driver modules on updates to kernel. 

The 'issue' I raised it not a bug, but more a question. I could not find any other way to ask questions. I will have to look into DMKS to see if it can automatically update the driver module each time the kernel gets updated. I know my graphics driver gets updated automatically each time the kernel updates. I was not sure how to create the triggers for the keyboard driver. Thanks for your quick response.

Please let me know if anything is not clear.

**Comment by XenHat** [comment]
Thanks, that's much more informative. :)
You should probably also look if the G3 and G4 keys not working are a known issue, and if not, fill an issue about it. In the meantime I'll see what my laptop thinks of my own G710+

**Comment by Wattos** [comment]
Apologies for the late response. There is a dkms.conf file and the driver should support automatic recompilation on kernel changes.Try running 

```
dkms add -m hid-lg-g710-plus -v 0.1
dkms install hid-lg-g710-plus/0.1
```

in the src/kernel directory.

When it comes to they custom keys, it seems that the driver is working fine. Have you tried running

```
 xmodmap misc/.Xmodmap
```

It may be that the keyboard is triggering the key events, but the XServer has not bound these to any key, therefore it seems as if the keys are not working.

**Comment by wxl** [comment]
It seems `dkms` is looking for `/usr/src/hid-lg-g710-plus-0.1`, which doesn't exist. One needs to move the contents of `src/kernel` (including `dkms.conf` of course) there first.

**Comment by mcrajah** [comment]
Hi Wattos and wxl, I managed to get it work, I had to follow wxl's instructions and drop the files in /usr/src/hid-lg-g710-plus-0.1 folder. 
@Wattos, after doing the xmodmap, all keys are working. It apprears that I have to do it every time I reboot, so I will add it to start up scripts. I am also able to see the the led_keys and led_macro files in /sys... folder. They work like a charm. I will now wait for the next kernel update to see if dkms is doing what its supposed to do. Thanks for all your support.

**Comment by gerardlouw** [comment]
For anyone coming here years later, this sequence of commands worked for me:

```
git clone https://github.com/Wattos/logitech-g710-linux-driver.git
cd logitech-g710-linux-driver
make
sudo dkms add src/kernel
sudo dkms install hid-lg-g710-plus/0.1
```
